/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crasy_words;

/**
 *
 * @author kevga
 */
public class Accueil extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    public Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_NewGame = new javax.swing.JButton();
        btn_Options = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        pnl_playernumber = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbb_playernumber = new javax.swing.JComboBox<>();
        btn_Begin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(610, 377));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crazy Words");

        btn_NewGame.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        btn_NewGame.setText("Nouvelle partie");
        btn_NewGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NewGameActionPerformed(evt);
            }
        });

        btn_Options.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        btn_Options.setText("Options");
        btn_Options.setMaximumSize(new java.awt.Dimension(120, 30));
        btn_Options.setMinimumSize(new java.awt.Dimension(120, 30));
        btn_Options.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_Options.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OptionsActionPerformed(evt);
            }
        });

        btn_Exit.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 12)); // NOI18N
        btn_Exit.setText("Quitter");
        btn_Exit.setMaximumSize(new java.awt.Dimension(120, 30));
        btn_Exit.setMinimumSize(new java.awt.Dimension(120, 30));
        btn_Exit.setPreferredSize(new java.awt.Dimension(120, 30));
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        pnl_playernumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnl_playernumber.setVisible(false);

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        jLabel2.setText("Nombre de joueurs :");

        cbb_playernumber.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 14)); // NOI18N
        cbb_playernumber.setMaximumRowCount(6);
        cbb_playernumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));

        btn_Begin.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 10)); // NOI18N
        btn_Begin.setLabel("Commencer");
        btn_Begin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BeginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_playernumberLayout = new javax.swing.GroupLayout(pnl_playernumber);
        pnl_playernumber.setLayout(pnl_playernumberLayout);
        pnl_playernumberLayout.setHorizontalGroup(
            pnl_playernumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_playernumberLayout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(pnl_playernumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(cbb_playernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Begin))
                .addGap(39, 39, 39))
        );
        pnl_playernumberLayout.setVerticalGroup(
            pnl_playernumberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_playernumberLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbb_playernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Begin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_NewGame)
                    .addComponent(btn_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnl_playernumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_NewGame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btn_Options, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnl_playernumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addComponent(btn_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_NewGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NewGameActionPerformed
        pnl_playernumber.setVisible(true);
    }//GEN-LAST:event_btn_NewGameActionPerformed

    private void btn_OptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OptionsActionPerformed
        setVisible(false);
    }//GEN-LAST:event_btn_OptionsActionPerformed

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExitActionPerformed
        dispose();
    }//GEN-LAST:event_btn_ExitActionPerformed

    private void btn_BeginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BeginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BeginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Begin;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JButton btn_NewGame;
    private javax.swing.JButton btn_Options;
    private javax.swing.JComboBox<String> cbb_playernumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel pnl_playernumber;
    // End of variables declaration//GEN-END:variables
}
